apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api-gateway
  template:
    metadata:
      labels:
        name: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: africkinbear/api-gateway:latest
          ports:
          - containerPort: 8000