apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
spec:
  type: ClusterIP
  selector:
    name: api-gateway
  ports:
    - name: tcp
      protocol: TCP
      port: 8000
      targetPort: 8000