apiVersion: v1
kind: Service
metadata:
  name: microservice-ui-svc
spec:
  type: ClusterIP
  selector:
    app: microservice-ui
  ports:
    - name: tcp
      protocol: TCP
      port: 3000
      targetPort: 3000