apiVersion: v1
kind: Service
metadata:
  name: service-registry-svc
spec:
  type: ClusterIP
  selector:
    name: service-registry
  ports:
    - name: tcp
      protocol: TCP
      port: 8761
      targetPort: 8761